import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
function server(emailFails=false){const rows=[],emails=[];const sheet={getLastRow:()=>rows.length+1,appendRow:r=>rows.push(r),getRange:(...args)=>args.length===4?{createTextFinder:id=>({matchEntireCell:()=>({findNext:()=>rows.some(r=>r[0]===id)})})}:{setValue:v=>rows.at(-1)[5]=v}};const context={PropertiesService:{getScriptProperties:()=>({getProperty:()=> 'sheet'})},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock:()=>{}})},SpreadsheetApp:{openById:()=>({getSheetByName:()=>sheet})},MailApp:{sendEmail:e=>{if(emailFails)throw Error('quota');emails.push(e);}},Utilities:{formatDate:()=> 'server date'},HtmlService:{createHtmlOutput:s=>s}};vm.createContext(context);vm.runInContext(fs.readFileSync('google-apps-script/Code.gs','utf8'),context);return {context,rows,emails};}
const data={id:'12345678-1234-1234-1234-123456789012',name:'Laia',summary:'He après a calcular la mediana.',responses:[{section:'Activitat',answers:[{resposta:5}]}]};
test('server stores immutable received copy and deduplicates same request',()=>{const s=server();const event={parameter:{payload:JSON.stringify(data)}};assert.match(s.context.doPost(event),/Treball rebut i desat/);assert.equal(s.rows.length,1);assert.equal(s.emails[0].to,'a8870408@xtec.cat');assert.match(s.context.doPost(event),/ja registrat/);assert.equal(s.rows.length,1);});
test('email failure still preserves submission and reports accurate receipt',()=>{const s=server(true);assert.match(s.context.doPost({parameter:{payload:JSON.stringify(data)}}),/notificació per correu no ha funcionat/);assert.equal(s.rows.length,1);});
test('rejects empty summary and escapes receipt and spreadsheet formulas',()=>{const s=server();assert.match(s.context.doPost({parameter:{payload:JSON.stringify({...data,summary:''})}}),/No s’ha confirmat/);assert.equal(s.rows.length,0);assert.equal(s.context.literal('=IMPORTXML()'),"'=IMPORTXML()");assert.ok(!s.context.receipt('<script>','<img>').includes('<script>'));});
