import {submissionEndpoint, isSubmissionEndpoint} from './submission-config.js?v=espai-4';
const key='aula-submission';
export function readSubmission(){try{return JSON.parse(localStorage.getItem(key)||'{}')||{};}catch{return {};}}
export function saveResponse(section,data){const report=readSubmission();report[section]=data;try{localStorage.setItem(key,JSON.stringify(report));}catch{} }
export function reportText(report){return ['Dades.cat · Respostes de l’alumne',`Nom: ${report.name||'(sense nom)'}`,...Object.entries(report).filter(([k])=>k!=='name').map(([section,data])=>`\n${section}\n${typeof data==='string'?data:JSON.stringify(data,null,2)}`)].join('\n');}
export function submissionPage(content){
const report=readSubmission();
content.innerHTML=`<div class="breadcrumb">El teu espai / Lliura les respostes</div><h1 class="page-title">Explica què has après</h1><p class="lead">Escriu un resum amb les teves paraules i lliura el treball al professorat.</p><form class="panel" id="send-form"><label for="student-name">Nom de l’alumne</label><input id="student-name" required maxlength="100" autocomplete="name"><label for="student-summary">El meu resum</label><textarea id="student-summary" required minlength="20" maxlength="3000" rows="5" placeholder="Què has après? Explica una descoberta amb dades, un càlcul i un dubte que encara tinguis."></textarea><p class="small">Entre 20 i 3.000 caràcters. El nom, el resum i les respostes es compartiran amb el professorat i es desaran al seu full. El servei notificarà a a8870408@xtec.cat. En un dispositiu compartit, esborra les dades quan acabis.</p><label for="report-preview">Revisa les respostes que lliuraràs</label><textarea id="report-preview" readonly rows="12"></textarea><button class="primary" ${submissionEndpoint?'':'disabled'}>Lliura les respostes →</button><p id="send-status" role="status">${submissionEndpoint?'Servei connectat · versió 2. La confirmació de recepció s’obrirà en una altra pestanya.':'El professorat encara ha d’activar el servei de lliuraments. Pots preparar i desar el resum mentrestant.'}</p></form>`;
const name=content.querySelector('#student-name'),summary=content.querySelector('#student-summary'),preview=content.querySelector('#report-preview'),status=content.querySelector('#send-status');
name.value=report.name||'';summary.value=report['Resum']||'';
const refresh=()=>{report.name=name.value.trim();report['Resum']=summary.value.trim();preview.value=reportText(report);};refresh();name.oninput=refresh;summary.oninput=refresh;name.onchange=()=>saveResponse('name',name.value.trim());summary.onchange=()=>saveResponse('Resum',summary.value.trim());
const feedback=document.createElement('section');feedback.className='panel';feedback.innerHTML='<h2>Consulta el feedback del professorat</h2><label for="receipt-id">Identificador del lliurament</label><input id="receipt-id" placeholder="Copia l’identificador de la confirmació"><button class="secondary" type="button" id="view-feedback">Consulta la revisió ↗</button><p class="small">Conserva aquest identificador i no el comparteixis: permet consultar el teu feedback. El nom no serveix per cercar treballs d’altres alumnes.</p><p id="feedback-status" role="status"></p>';content.append(feedback);try{content.querySelector('#receipt-id').value=localStorage.getItem('aula-last-receipt')||'';}catch{}
content.querySelector('#view-feedback').onclick=()=>{const id=content.querySelector('#receipt-id').value.trim();if(!/^[a-f0-9-]{36}$/i.test(id)||!isSubmissionEndpoint(submissionEndpoint)){content.querySelector('#feedback-status').textContent='Indica un identificador vàlid i comprova que el servei estigui connectat.';return;}window.open(submissionEndpoint+'?feedback='+encodeURIComponent(id),'_blank','noopener');};
let pendingId=null;let pendingPayload=null;
content.querySelector('#send-form').onsubmit=e=>{e.preventDefault();refresh();if(!report.name||report['Resum'].length<20){status.textContent='Indica el nom i escriu un resum de com a mínim 20 caràcters.';return;}
const responses=Object.entries(report).filter(([k])=>!['name','Resum'].includes(k)).map(([section,answers])=>({section,answers}));if(!responses.length){status.textContent='Completa i comprova alguna activitat abans de lliurar el treball.';return;}
if(!isSubmissionEndpoint(submissionEndpoint)){status.textContent='El servei de lliuraments encara no està configurat correctament.';return;}
saveResponse('name',report.name);saveResponse('Resum',report['Resum']);const snapshot=JSON.stringify({name:report.name,summary:report['Resum'],responses});if(snapshot!==pendingPayload){pendingId=crypto.randomUUID();pendingPayload=snapshot;}const payload=JSON.stringify({id:pendingId,...JSON.parse(snapshot)});if(payload.length>45000){status.textContent='El treball és massa llarg per lliurar-lo. Redueix les dades del laboratori i torna-ho a provar.';return;}
const form=document.createElement('form');form.method='POST';form.action=submissionEndpoint;form.target='_blank';form.rel='noopener';const field=document.createElement('input');field.type='hidden';field.name='payload';field.value=payload;form.append(field);document.body.append(form);form.submit();form.remove();try{localStorage.setItem('aula-last-receipt',pendingId);const history=JSON.parse(localStorage.getItem('aula-receipts')||'[]');if(Array.isArray(history)&&!history.some(r=>r.id===pendingId)){history.push({id:pendingId,name:report.name,date:new Date().toISOString()});localStorage.setItem('aula-receipts',JSON.stringify(history));}content.querySelector('#receipt-id').value=pendingId;}catch{}status.textContent='S’ha obert el servei de lliuraments. Comprova que la nova pestanya mostri «Treball rebut i desat». Si no s’obre, permet les finestres emergents i torna-ho a provar.';
};}

export function studentSpace(content){
  content.innerHTML='<div class="breadcrumb">El teu espai / El meu espai</div><h1 class="page-title">Els teus treballs i el teu feedback</h1><p class="lead">Obre un lliurament per veure les respostes, la correcció i els comentaris del professorat.</p><section class="panel"><h2>Els meus lliuraments en aquest navegador</h2><div id="my-receipts"></div><p class="small">Només es mostren els identificadors desats en aquest navegador. Si utilitzes un altre dispositiu, introdueix el teu identificador privat.</p></section><form class="panel" id="open-space"><label for="space-id">Identificador privat del lliurament</label><input id="space-id" required placeholder="Identificador que apareix a la confirmació"><button class="primary">Obre el meu dashboard ↗</button><p id="space-status" role="status"></p><p class="small">No comparteixis aquest identificador. No és un accés amb contrasenya: qui el tingui pot consultar el teu treball. En un dispositiu compartit, esborra les dades des d’«El meu progrés».</p></form>';
  let receipts=[];try{receipts=JSON.parse(localStorage.getItem('aula-receipts')||'[]');const last=localStorage.getItem('aula-last-receipt');if(last&&!receipts.some(r=>r.id===last))receipts.push({id:last,date:'',name:'Darrer lliurament'});}catch{}if(!Array.isArray(receipts))receipts=[];
  const list=content.querySelector('#my-receipts');if(!receipts.length)list.textContent='Encara no hi ha lliuraments desats aquí.';receipts.slice().reverse().forEach(r=>{const button=document.createElement('button');button.className='secondary';button.style.margin='6px';button.textContent=(r.name||'Lliurament')+(r.date?' · '+new Date(r.date).toLocaleDateString('ca-ES'):'');button.onclick=()=>{content.querySelector('#space-id').value=r.id;open(r.id);};list.append(button);});
  function open(id){if(!/^[a-f0-9-]{36}$/i.test(id)||!isSubmissionEndpoint(submissionEndpoint)){content.querySelector('#space-status').textContent='Comprova l’identificador i la configuració del servei.';return;}window.open(submissionEndpoint+'?feedback='+encodeURIComponent(id),'_blank','noopener');content.querySelector('#space-status').textContent='El teu dashboard s’obre en una altra pestanya. Només el servei pot confirmar que el treball està rebut.';}
  content.querySelector('#open-space').onsubmit=e=>{e.preventDefault();open(content.querySelector('#space-id').value.trim());};
}
