import {submissionEndpoint, isSubmissionEndpoint} from './submission-config.js?v=lliuraments-2';
const key='aula-submission';
export function readSubmission(){try{return JSON.parse(localStorage.getItem(key)||'{}')||{};}catch{return {};}}
export function saveResponse(section,data){const report=readSubmission();report[section]=data;try{localStorage.setItem(key,JSON.stringify(report));}catch{} }
export function reportText(report){return ['Dades.cat · Respostes de l’alumne',`Nom: ${report.name||'(sense nom)'}`,...Object.entries(report).filter(([k])=>k!=='name').map(([section,data])=>`\n${section}\n${typeof data==='string'?data:JSON.stringify(data,null,2)}`)].join('\n');}
export function submissionPage(content){
const report=readSubmission();
content.innerHTML=`<div class="breadcrumb">El teu espai / Lliura les respostes</div><h1 class="page-title">Explica què has après</h1><p class="lead">Escriu un resum amb les teves paraules i lliura el treball al professorat.</p><form class="panel" id="send-form"><label for="student-name">Nom de l’alumne</label><input id="student-name" required maxlength="100" autocomplete="name"><label for="student-summary">El meu resum</label><textarea id="student-summary" required minlength="20" maxlength="3000" rows="5" placeholder="Què has après? Explica una descoberta amb dades, un càlcul i un dubte que encara tinguis."></textarea><p class="small">Entre 20 i 3.000 caràcters. El nom, el resum i les respostes es compartiran amb el professorat i es desaran al seu full. El servei notificarà a a8870408@xtec.cat. En un dispositiu compartit, esborra les dades quan acabis.</p><label for="report-preview">Revisa les respostes que lliuraràs</label><textarea id="report-preview" readonly rows="12"></textarea><button class="primary" ${submissionEndpoint?'':'disabled'}>Lliura les respostes →</button><p id="send-status" role="status">${submissionEndpoint?'Servei connectat · versió 2. La confirmació de recepció s’obrirà en una altra pestanya.':'El professorat encara ha d’activar el servei de lliuraments. Pots preparar i desar el resum mentrestant.'}</p></form>`;
const name=content.querySelector('#student-name'),summary=content.querySelector('#student-summary'),preview=content.querySelector('#report-preview'),status=content.querySelector('#send-status');
name.value=report.name||'';summary.value=report['Resum']||'';
const refresh=()=>{report.name=name.value.trim();report['Resum']=summary.value.trim();preview.value=reportText(report);};refresh();name.oninput=refresh;summary.oninput=refresh;name.onchange=()=>saveResponse('name',name.value.trim());summary.onchange=()=>saveResponse('Resum',summary.value.trim());
let pendingId=null;let pendingPayload=null;
content.querySelector('#send-form').onsubmit=e=>{e.preventDefault();refresh();if(!report.name||report['Resum'].length<20){status.textContent='Indica el nom i escriu un resum de com a mínim 20 caràcters.';return;}
const responses=Object.entries(report).filter(([k])=>!['name','Resum'].includes(k)).map(([section,answers])=>({section,answers}));if(!responses.length){status.textContent='Completa i comprova alguna activitat abans de lliurar el treball.';return;}
if(!isSubmissionEndpoint(submissionEndpoint)){status.textContent='El servei de lliuraments encara no està configurat correctament.';return;}
saveResponse('name',report.name);saveResponse('Resum',report['Resum']);const snapshot=JSON.stringify({name:report.name,summary:report['Resum'],responses});if(snapshot!==pendingPayload){pendingId=crypto.randomUUID();pendingPayload=snapshot;}const payload=JSON.stringify({id:pendingId,...JSON.parse(snapshot)});if(payload.length>45000){status.textContent='El treball és massa llarg per lliurar-lo. Redueix les dades del laboratori i torna-ho a provar.';return;}
const form=document.createElement('form');form.method='POST';form.action=submissionEndpoint;form.target='_blank';form.rel='noopener';const field=document.createElement('input');field.type='hidden';field.name='payload';field.value=payload;form.append(field);document.body.append(form);form.submit();form.remove();status.textContent='S’ha obert el servei de lliuraments. Comprova que la nova pestanya mostri «Treball rebut i desat». Si no s’obre, permet les finestres emergents i torna-ho a provar.';
};}
